version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - ENABLE_TRACING=true # Keep it on for dev to see traces
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s # Faster start for dev

  nginx:
    ports:
      - "8080:80" # Use a different port to avoid conflicts
      - "8443:443" 