services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - DEBUG=true
    depends_on:
      - qdrant
    volumes:
      - ./src:/app/src  # Mount source code for development
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.9.2
    ports:
      - "6333:6333" # HTTP API port
      - "6334:6334" # gRPC port
    volumes:
      - qdata:/qdrant/storage
    restart: unless-stopped

volumes:
  qdata:
    driver: local
