services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - DEBUG=true
    depends_on:
      qdrant:
        condition: service_healthy
    volumes:
      - ./src:/app/src  # Mount source code for development
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:v1.9.2
    ports:
      - "6333:6333"
      - "6334:6334"  # HTTP API port
    volumes:
      - qdata:/qdrant/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/local/bin/health_check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  qdata:
    driver: local
