secrets:
  qdrant_api_key:
    file: ./secrets/qdrant_api_key
  openai_api_key:
    file: ./secrets/openai_api_key

networks:
  saathy-net:
    driver: bridge

volumes:
  qdata:
    driver: local

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saathy-api-test
    restart: unless-stopped
    depends_on:
      - qdrant
    networks:
      - saathy-net
    environment:
      - ENVIRONMENT=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_API_KEY_FILE=/run/secrets/qdrant_api_key
      - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key
    secrets:
      - qdrant_api_key
      - openai_api_key
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

  qdrant:
    image: qdrant/qdrant:v1.9.2
    container_name: saathy-qdrant-test
    restart: unless-stopped
    ports:
      - "6333:6333"
    networks:
      - saathy-net
    volumes:
      - qdata:/qdrant/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
