---
- name: Deploy Saathy to Production
  hosts: prod
  become: yes
  vars:
    github_owner: "{{ lookup('env', 'GITHUB_REPOSITORY_OWNER') | default('your-username') }}"
    github_sha: "{{ lookup('env', 'GITHUB_SHA') | default('latest') }}"

  roles:
    - docker
    - compose

  tasks:
    - name: Display deployment info
      debug:
        msg: |
          Deploying Saathy to production
          Image: ghcr.io/{{ github_owner }}/saathy-oss:{{ github_sha }}
          Target: {{ inventory_hostname }}

    - name: Wait for containers to be healthy
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 80
        delay: 10
        timeout: 300 