[tool.poetry]
name = "saathy-chunking"
version = "0.1.0"
description = "Text chunking strategies for Saathy"
authors = ["Saathy Team"]
readme = "README.md"
packages = [{include = "saathy_chunking", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
saathy-core = {path = "../saathy-core", develop = true}
tiktoken = "^0.5.0"
nltk = "^3.8"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.0.0"
ruff = "^0.1.0"
mypy = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"