[tool.poetry]
name = "saathy-intelligence"
version = "0.1.0"
description = "AI-powered intelligence features for Saathy"
authors = ["Saathy Team"]
readme = "README.md"
packages = [{include = "saathy_intelligence", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
saathy-core = {path = "../saathy-core", develop = true}
openai = "^1.0.0"
langchain = "^0.1.0"
scikit-learn = "^1.3.0"
numpy = "^1.24.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.0.0"
ruff = "^0.1.0"
mypy = "^1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"