name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests and Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry config virtualenvs.create false

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run linters
        run: poetry run ruff check .

      - name: Run unit tests
        run: poetry run pytest

  integration-test:
    name: Build and Smoke Test
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        config:
          - { name: "Development", compose_file: "docker-compose.dev.yml", env: "dev", port: 8000, base_url: "http://localhost:8000", service: "api" }
          - { name: "Production", compose_file: "docker-compose.prod.yml", env: "prod", port: 80, base_url: "http://localhost", service: "nginx" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and start services
        run: docker-compose -f ${{ matrix.config.compose_file }} up -d --build

      - name: Wait for Qdrant to be ready
        run: |
          echo "Waiting for Qdrant to be ready on port 6333..."
          max_wait=60
          current_wait=0
          while ! nc -z localhost 6333; do
            if [ $current_wait -ge $max_wait ]; then
              echo "Error: Timeout waiting for Qdrant to be ready."
              docker-compose -f ${{ matrix.config.compose_file }} logs qdrant
              exit 1
            fi
            sleep 2
            current_wait=$((current_wait + 2))
          done
          echo "Qdrant is ready."

      - name: Wait for API to be ready
        run: |
          echo "Waiting for API to be ready on port ${{ matrix.config.port }}..."
          max_wait=120
          current_wait=0
          while ! nc -z localhost ${{ matrix.config.port }}; do
            if [ $current_wait -ge $max_wait ]; then
              echo "Error: Timeout waiting for API to be ready."
              docker-compose -f ${{ matrix.config.compose_file }} logs ${{ matrix.config.service }}
              exit 1
            fi
            sleep 5
            current_wait=$((current_wait + 5))
          done
          echo "API is ready."

      - name: Wait for API readiness endpoint
        run: |
          echo "Waiting for API readiness endpoint..."
          max_wait=60
          current_wait=0
          while true; do
            if [ $current_wait -ge $max_wait ]; then
              echo "Error: Timeout waiting for API readiness endpoint."
              curl -f ${{ matrix.config.base_url }}/readyz || echo "Readiness check failed"
              docker-compose -f ${{ matrix.config.compose_file }} logs ${{ matrix.config.service }}
              exit 1
            fi
            
            # Try to get readiness status
            response=$(curl -s ${{ matrix.config.base_url }}/readyz 2>/dev/null || echo "")
            if echo "$response" | grep -q '"status":"ready"'; then
              echo "API readiness endpoint is ready."
              break
            fi
            
            sleep 5
            current_wait=$((current_wait + 5))
          done

      - name: Wait for health endpoint to be healthy
        run: |
          echo "Waiting for health endpoint to return healthy status..."
          max_wait=60
          current_wait=0
          while true; do
            if [ $current_wait -ge $max_wait ]; then
              echo "Error: Timeout waiting for health endpoint to be healthy."
              curl -f ${{ matrix.config.base_url }}/healthz || echo "Health check failed"
              docker-compose -f ${{ matrix.config.compose_file }} logs ${{ matrix.config.service }}
              exit 1
            fi
            
            # Try to get health status
            response=$(curl -s ${{ matrix.config.base_url }}/healthz 2>/dev/null || echo "")
            if echo "$response" | grep -q '"status":"healthy"'; then
              echo "Health endpoint is healthy."
              break
            fi
            
            sleep 5
            current_wait=$((current_wait + 5))
          done

      - name: Install test dependencies
        run: pip install requests colorama

      - name: Run smoke test
        run: |
          python scripts/smoke_test.py --base-url ${{ matrix.config.base_url }} --timeout 5.0
        env:
          ENV_FOR_TEST: ${{ matrix.config.env }}

      - name: Show logs on failure
        if: failure()
        run: |
          echo "=== API Logs ==="
          docker-compose -f ${{ matrix.config.compose_file }} logs ${{ matrix.config.service }}
          echo "=== Qdrant Logs ==="
          docker-compose -f ${{ matrix.config.compose_file }} logs qdrant
